version: '2.1'

services:
  awesome-angular-workshop:
    image: awesome-angular-workshop
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9070:9070
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js